name: pgn_parser
version: 0.0.0
description: Pgn parser
author: Alexis Vargas <lexisvar@gmail.com>
homepage: https://github.com/lexisvar/pgn-parser.dart
dev_dependencies:
  test: ^1.12.0 
environment:
  sdk: '>=2.0.0 <3.0.0'