name: pgn_parser
version: 0.0.0
description: Pgn parser
author: Alexis Vargas <lexisvar@gmail.com>
homepage: https://github.com/lexisvar/pgn-parser.dart
dependencies:
  browser: ">=0.8.1 <0.8.2"
  test: ^1.12.0
dev_dependencies:
  unittest: any
  plummbur_kruk: any